import ExcelJS from 'exceljs';
import type { Inquiry, User } from '../drizzle/schema';

interface InquiryItem {
  id: number;
  productId: number;
  quantity: number;
  notes: string | null;
  product: {
    id: number;
    productId: string;
    partNumber: string;
    brand: string;
    name: string | null;
    description: string | null;
  } | null;
}

/**
 * Generate Excel file for inquiry
 */
export async function generateInquiryExcel(
  inquiry: Inquiry,
  items: InquiryItem[],
  user: User
): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet('Inquiry');

  // Set column widths
  worksheet.columns = [
    { width: 5 },   // No.
    { width: 25 },  // Product ID
    { width: 20 },  // Brand
    { width: 20 },  // Part Number
    { width: 35 },  // Product Name
    { width: 10 },  // Quantity
    { width: 30 },  // Notes
  ];

  // Header Section
  worksheet.mergeCells('A1:G1');
  const titleRow = worksheet.getCell('A1');
  titleRow.value = 'ROWELL HPLC - Product Inquiry';
  titleRow.font = { size: 16, bold: true };
  titleRow.alignment = { horizontal: 'center', vertical: 'middle' };
  worksheet.getRow(1).height = 30;

  // Inquiry Information
  worksheet.addRow([]);
  worksheet.addRow(['Inquiry Number:', inquiry.inquiryNumber]);
  worksheet.addRow(['Date:', new Date(inquiry.createdAt).toLocaleString()]);
  worksheet.addRow(['Status:', inquiry.status.toUpperCase()]);
  worksheet.addRow(['Urgency:', inquiry.urgency.replace('_', ' ').toUpperCase()]);
  
  // Customer Information
  worksheet.addRow([]);
  worksheet.addRow(['CUSTOMER INFORMATION']);
  worksheet.getCell('A8').font = { bold: true, size: 12 };
  worksheet.addRow(['Name:', user.name || 'N/A']);
  worksheet.addRow(['Email:', user.email || 'N/A']);
  worksheet.addRow(['Company:', user.company || 'N/A']);
  worksheet.addRow(['Phone:', user.phone || 'N/A']);
  worksheet.addRow(['Country:', user.country || 'N/A']);

  // Inquiry Details
  if (inquiry.budgetRange || inquiry.applicationNotes || inquiry.deliveryAddress || inquiry.customerNotes) {
    worksheet.addRow([]);
    worksheet.addRow(['INQUIRY DETAILS']);
    worksheet.getCell(`A${worksheet.lastRow!.number}`).font = { bold: true, size: 12 };
    
    if (inquiry.budgetRange) {
      worksheet.addRow(['Budget Range:', inquiry.budgetRange]);
    }
    if (inquiry.applicationNotes) {
      worksheet.addRow(['Application Notes:', inquiry.applicationNotes]);
    }
    if (inquiry.deliveryAddress) {
      worksheet.addRow(['Delivery Address:', inquiry.deliveryAddress]);
    }
    if (inquiry.customerNotes) {
      worksheet.addRow(['Additional Notes:', inquiry.customerNotes]);
    }
  }

  // Products Table
  worksheet.addRow([]);
  const productsHeaderRow = worksheet.addRow(['PRODUCTS']);
  productsHeaderRow.getCell(1).font = { bold: true, size: 12 };
  
  // Table Header
  const tableHeaderRow = worksheet.addRow([
    'No.',
    'Product ID',
    'Brand',
    'Part Number',
    'Product Name',
    'Quantity',
    'Notes'
  ]);
  
  tableHeaderRow.eachCell((cell) => {
    cell.font = { bold: true };
    cell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFE0E0E0' }
    };
    cell.border = {
      top: { style: 'thin' },
      left: { style: 'thin' },
      bottom: { style: 'thin' },
      right: { style: 'thin' }
    };
  });

  // Table Data
  items.forEach((item, index) => {
    const row = worksheet.addRow([
      index + 1,
      item.product?.productId || 'N/A',
      item.product?.brand || 'N/A',
      item.product?.partNumber || 'N/A',
      item.product?.name || 'N/A',
      item.quantity,
      item.notes || ''
    ]);

    row.eachCell((cell) => {
      cell.border = {
        top: { style: 'thin' },
        left: { style: 'thin' },
        bottom: { style: 'thin' },
        right: { style: 'thin' }
      };
    });
  });

  // Summary
  worksheet.addRow([]);
  worksheet.addRow(['Total Items:', items.length]);
  worksheet.getCell(`A${worksheet.lastRow!.number}`).font = { bold: true };

  // Footer
  worksheet.addRow([]);
  worksheet.addRow([]);
  const footerRow = worksheet.addRow(['Generated by ROWELL HPLC Inquiry System']);
  footerRow.getCell(1).font = { italic: true, size: 10 };
  footerRow.getCell(1).alignment = { horizontal: 'center' };
  worksheet.mergeCells(`A${footerRow.number}:G${footerRow.number}`);

  // Generate buffer
  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

/**
 * Send inquiry email notification to admin
 * This is a business notification email (not marketing)
 */
export async function sendInquiryEmail(
  inquiry: Inquiry,
  user: User,
  excelBuffer: Buffer
): Promise<boolean> {
  try {
    const sgMail = (await import('@sendgrid/mail')).default;
    const apiKey = process.env.SENDGRID_API_KEY;
    const fromEmail = process.env.SENDGRID_FROM_EMAIL || 'noreply@rowellhplc.com';
    const toEmail = 'info@rowellhplc.com';

    if (!apiKey) {
      console.warn('[Email] SENDGRID_API_KEY not configured, skipping email');
      return false;
    }

    sgMail.setApiKey(apiKey);

    const msg = {
      to: toEmail,
      from: fromEmail,
      subject: `New Inquiry: ${inquiry.inquiryNumber} from ${user.name || user.email}`,
      text: `
New inquiry received from ROWELL HPLC website.

Inquiry Number: ${inquiry.inquiryNumber}
Customer: ${user.name || 'N/A'}
Email: ${user.email}
Company: ${user.company || 'N/A'}
Phone: ${user.phone || 'N/A'}
Country: ${user.country || 'N/A'}
Urgency: ${inquiry.urgency.replace('_', ' ').toUpperCase()}
Budget Range: ${inquiry.budgetRange || 'N/A'}

Please check the attached Excel file for detailed product list.
      `,
      html: `
<h2>New Inquiry Received</h2>
<p>A new inquiry has been submitted from the ROWELL HPLC website.</p>

<h3>Inquiry Information</h3>
<ul>
  <li><strong>Inquiry Number:</strong> ${inquiry.inquiryNumber}</li>
  <li><strong>Date:</strong> ${new Date(inquiry.createdAt).toLocaleString()}</li>
  <li><strong>Status:</strong> ${inquiry.status.toUpperCase()}</li>
  <li><strong>Urgency:</strong> ${inquiry.urgency.replace('_', ' ').toUpperCase()}</li>
  <li><strong>Budget Range:</strong> ${inquiry.budgetRange || 'N/A'}</li>
</ul>

<h3>Customer Information</h3>
<ul>
  <li><strong>Name:</strong> ${user.name || 'N/A'}</li>
  <li><strong>Email:</strong> ${user.email}</li>
  <li><strong>Company:</strong> ${user.company || 'N/A'}</li>
  <li><strong>Phone:</strong> ${user.phone || 'N/A'}</li>
  <li><strong>Country:</strong> ${user.country || 'N/A'}</li>
</ul>

<p>Please check the attached Excel file for the detailed product list.</p>
      `,
      attachments: [
        {
          content: excelBuffer.toString('base64'),
          filename: `inquiry-${inquiry.inquiryNumber}.xlsx`,
          type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
          disposition: 'attachment',
        },
      ],
    };

    await sgMail.send(msg);
    console.log(`[Email] Inquiry notification sent to ${toEmail}`);
    return true;
  } catch (error) {
    console.error('[Email] Failed to send inquiry email:', error);
    return false;
  }
}

/**
 * Send confirmation email to customer
 * This is a business notification email (not marketing)
 */
export async function sendCustomerConfirmationEmail(
  inquiry: Inquiry,
  user: User
): Promise<boolean> {
  try {
    const sgMail = (await import('@sendgrid/mail')).default;
    const apiKey = process.env.SENDGRID_API_KEY;
    const fromEmail = process.env.SENDGRID_FROM_EMAIL || 'noreply@rowellhplc.com';

    if (!apiKey) {
      console.warn('[Email] SENDGRID_API_KEY not configured, skipping email');
      return false;
    }

    if (!user.email) {
      console.warn('[Email] Customer email not available, skipping confirmation');
      return false;
    }

    sgMail.setApiKey(apiKey);

    const msg = {
      to: user.email,
      from: fromEmail,
      subject: `Inquiry ${inquiry.inquiryNumber} Received - ROWELL HPLC`,
      text: `
Dear ${user.name || 'Customer'},

Thank you for your inquiry! We have received your product inquiry and our team will review it shortly.

Inquiry Number: ${inquiry.inquiryNumber}
Date: ${new Date(inquiry.createdAt).toLocaleString()}
Urgency: ${inquiry.urgency.replace('_', ' ').toUpperCase()}

Our sales team will contact you within 24-48 hours with a detailed quotation.

If you have any questions, please don't hesitate to contact us at info@rowellhplc.com.

Best regards,
ROWELL HPLC Team
      `,
      html: `
<h2>Thank You for Your Inquiry!</h2>
<p>Dear ${user.name || 'Customer'},</p>

<p>We have received your product inquiry and our team will review it shortly.</p>

<h3>Inquiry Details</h3>
<ul>
  <li><strong>Inquiry Number:</strong> ${inquiry.inquiryNumber}</li>
  <li><strong>Date:</strong> ${new Date(inquiry.createdAt).toLocaleString()}</li>
  <li><strong>Urgency:</strong> ${inquiry.urgency.replace('_', ' ').toUpperCase()}</li>
</ul>

<p>Our sales team will contact you within <strong>24-48 hours</strong> with a detailed quotation.</p>

<p>If you have any questions, please don't hesitate to contact us at <a href="mailto:info@rowellhplc.com">info@rowellhplc.com</a>.</p>

<p>Best regards,<br>
<strong>ROWELL HPLC Team</strong></p>
      `,
    };

    await sgMail.send(msg);
    console.log(`[Email] Confirmation email sent to ${user.email}`);
    return true;
  } catch (error) {
    console.error('[Email] Failed to send confirmation email:', error);
    return false;
  }
}

