import ExcelJS from 'exceljs';
import type { Inquiry, User } from '../drizzle/schema';

interface InquiryItem {
  id: number;
  productId: number;
  quantity: number;
  notes: string | null;
  product: {
    id: number;
    productId: string;
    partNumber: string;
    brand: string;
    name: string | null;
    description: string | null;
  } | null;
}

/**
 * Generate Excel file for inquiry
 */
export async function generateInquiryExcel(
  inquiry: Inquiry,
  items: InquiryItem[],
  user: User
): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet('Inquiry');

  // Set column widths
  worksheet.columns = [
    { width: 5 },   // No.
    { width: 25 },  // Product ID
    { width: 20 },  // Brand
    { width: 20 },  // Part Number
    { width: 35 },  // Product Name
    { width: 10 },  // Quantity
    { width: 30 },  // Notes
  ];

  // Header Section
  worksheet.mergeCells('A1:G1');
  const titleRow = worksheet.getCell('A1');
  titleRow.value = 'ROWELL HPLC - Product Inquiry';
  titleRow.font = { size: 16, bold: true };
  titleRow.alignment = { horizontal: 'center', vertical: 'middle' };
  worksheet.getRow(1).height = 30;

  // Inquiry Information
  worksheet.addRow([]);
  worksheet.addRow(['Inquiry Number:', inquiry.inquiryNumber]);
  worksheet.addRow(['Date:', new Date(inquiry.createdAt).toLocaleString()]);
  worksheet.addRow(['Status:', inquiry.status.toUpperCase()]);
  worksheet.addRow(['Urgency:', inquiry.urgency.replace('_', ' ').toUpperCase()]);
  
  // Customer Information
  worksheet.addRow([]);
  worksheet.addRow(['CUSTOMER INFORMATION']);
  worksheet.getCell('A8').font = { bold: true, size: 12 };
  worksheet.addRow(['Name:', user.name || 'N/A']);
  worksheet.addRow(['Email:', user.email || 'N/A']);
  worksheet.addRow(['Company:', user.company || 'N/A']);
  worksheet.addRow(['Phone:', user.phone || 'N/A']);
  worksheet.addRow(['Country:', user.country || 'N/A']);

  // Inquiry Details
  if (inquiry.budgetRange || inquiry.applicationNotes || inquiry.deliveryAddress || inquiry.customerNotes) {
    worksheet.addRow([]);
    worksheet.addRow(['INQUIRY DETAILS']);
    worksheet.getCell(`A${worksheet.lastRow!.number}`).font = { bold: true, size: 12 };
    
    if (inquiry.budgetRange) {
      worksheet.addRow(['Budget Range:', inquiry.budgetRange]);
    }
    if (inquiry.applicationNotes) {
      worksheet.addRow(['Application Notes:', inquiry.applicationNotes]);
    }
    if (inquiry.deliveryAddress) {
      worksheet.addRow(['Delivery Address:', inquiry.deliveryAddress]);
    }
    if (inquiry.customerNotes) {
      worksheet.addRow(['Additional Notes:', inquiry.customerNotes]);
    }
  }

  // Products Table
  worksheet.addRow([]);
  const productsHeaderRow = worksheet.addRow(['PRODUCTS']);
  productsHeaderRow.getCell(1).font = { bold: true, size: 12 };
  
  // Table Header
  const tableHeaderRow = worksheet.addRow([
    'No.',
    'Product ID',
    'Brand',
    'Part Number',
    'Product Name',
    'Quantity',
    'Notes'
  ]);
  
  tableHeaderRow.eachCell((cell) => {
    cell.font = { bold: true };
    cell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFE0E0E0' }
    };
    cell.border = {
      top: { style: 'thin' },
      left: { style: 'thin' },
      bottom: { style: 'thin' },
      right: { style: 'thin' }
    };
  });

  // Table Data
  items.forEach((item, index) => {
    const row = worksheet.addRow([
      index + 1,
      item.product?.productId || 'N/A',
      item.product?.brand || 'N/A',
      item.product?.partNumber || 'N/A',
      item.product?.name || 'N/A',
      item.quantity,
      item.notes || ''
    ]);

    row.eachCell((cell) => {
      cell.border = {
        top: { style: 'thin' },
        left: { style: 'thin' },
        bottom: { style: 'thin' },
        right: { style: 'thin' }
      };
    });
  });

  // Summary
  worksheet.addRow([]);
  worksheet.addRow(['Total Items:', items.length]);
  worksheet.getCell(`A${worksheet.lastRow!.number}`).font = { bold: true };

  // Footer
  worksheet.addRow([]);
  worksheet.addRow([]);
  const footerRow = worksheet.addRow(['Generated by ROWELL HPLC Inquiry System']);
  footerRow.getCell(1).font = { italic: true, size: 10 };
  footerRow.getCell(1).alignment = { horizontal: 'center' };
  worksheet.mergeCells(`A${footerRow.number}:G${footerRow.number}`);

  // Generate buffer
  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

/**
 * Send inquiry email notification
 * Note: This is a placeholder. In production, you would use a real email service.
 */
export async function sendInquiryEmail(
  inquiry: Inquiry,
  user: User,
  excelBuffer: Buffer
): Promise<boolean> {
  try {
    // TODO: Implement actual email sending using a service like SendGrid, AWS SES, etc.
    // For now, we'll just log the email details
    console.log('[Email] Inquiry email notification:');
    console.log(`  To: info@rowellhplc.com`);
    console.log(`  Subject: New Inquiry ${inquiry.inquiryNumber} from ${user.name || user.email}`);
    console.log(`  Inquiry Number: ${inquiry.inquiryNumber}`);
    console.log(`  Customer: ${user.name} (${user.email})`);
    console.log(`  Company: ${user.company}`);
    console.log(`  Total Items: ${inquiry.totalItems}`);
    console.log(`  Excel attachment size: ${excelBuffer.length} bytes`);
    
    // In production, you would send the email here
    // Example with nodemailer:
    // const transporter = nodemailer.createTransport({...});
    // await transporter.sendMail({
    //   from: 'noreply@rowellhplc.com',
    //   to: 'info@rowellhplc.com',
    //   subject: `New Inquiry ${inquiry.inquiryNumber} from ${user.name || user.email}`,
    //   html: generateEmailHTML(inquiry, user),
    //   attachments: [{
    //     filename: `Inquiry_${inquiry.inquiryNumber}.xlsx`,
    //     content: excelBuffer
    //   }]
    // });

    return true;
  } catch (error) {
    console.error('[Email] Failed to send inquiry email:', error);
    return false;
  }
}

/**
 * Send confirmation email to customer
 */
export async function sendCustomerConfirmationEmail(
  inquiry: Inquiry,
  user: User
): Promise<boolean> {
  try {
    console.log('[Email] Customer confirmation email:');
    console.log(`  To: ${user.email}`);
    console.log(`  Subject: Inquiry ${inquiry.inquiryNumber} Received`);
    console.log(`  Customer: ${user.name}`);
    console.log(`  Inquiry Number: ${inquiry.inquiryNumber}`);
    
    // In production, send actual confirmation email to customer
    
    return true;
  } catch (error) {
    console.error('[Email] Failed to send confirmation email:', error);
    return false;
  }
}

